### ISSUE TITLE
Run ChessCoach without high end graphics card.

### ISSUE THREAD

**Issue by Jonathan003** [chrisbutner/ChessCoach#6]
I want to try ChessCoach but I don't have a high end graphics card.
I know I can't run Lela chess engine, ore it is very weak on my PC.
Stockfish 16 is very strong on my Windows 11 PC from 10 years old.
I don't want to install everyting to find out it is not working on my PC like it should.
Are there any updates planned so ChessCoach can be used wouthout high end graphics cards?

**Comment by chrisbutner** [comment]
If you're interested in using a strong engine without a high-end graphics card, Stockfish is probably your best bet, since ChessCoach has similar hardware requirements to Lc0. There are no updates planned that would change this.

If you're looking to generate move commentary though, that doesn't need a high-end graphics card: just one that is compatible with cuDNN.
